variables:
  DOCKER_REPO_NAME: "asap-sapg-backend"
  ANSIBLE_IMAGE: "999669/ansible-3.5:latest"
  KANIKO_IMAGE: "gcr.io/kaniko-project/executor:debug"

.setup_ssh: &setup_ssh
  - >
    mkdir -p ~/.ssh &&
    echo "$SSH_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/deploy &&
    chmod 600 ~/.ssh/deploy &&
    echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

stages:
  - build
  - deploy


.build-only: &build-only
  only:
    - master
    - dev
    - tags

build:
  stage: build
  <<: *build-only
  image:
    name: $KANIKO_IMAGE
    entrypoint: [""]
  script:
    - cp .env.example .env
    - echo "Run image building process"
    - echo "{\"auths\":{\"$DOCKER_REGESTRY_URL\":{\"username\":\"$DOCKER_REGESTRY_USERNAME\",\"password\":\"$DOCKER_REGESTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - >
      if [ ! -z $CI_COMMIT_TAG ]; then
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/$DOCKERFILE
      --destination $DOCKER_REGESTRY_URL/$DOCKER_REGESTRY_PROJECT/$REPO_NAME:$CI_COMMIT_TAG
      --destination $DOCKER_REGESTRY_URL/$DOCKER_REGESTRY_PROJECT/$REPO_NAME:$CI_COMMIT_SHORT_SHA
      --destination $DOCKER_REGESTRY_URL/$DOCKER_REGESTRY_PROJECT/$REPO_NAME:latest
      --cache=true; else
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/$DOCKERFILE
      --destination $DOCKER_REGESTRY_URL/$DOCKER_REGESTRY_PROJECT/$REPO_NAME:$CI_COMMIT_SHORT_SHA
      --destination $DOCKER_REGESTRY_URL/$DOCKER_REGESTRY_PROJECT/$REPO_NAME:latest
      --cache=true; fi
  variables:
    DOCKERFILE: .docker/Dockerfile
    REPO_NAME: $DOCKER_REPO_NAME

deploy-dev:
  stage: deploy
  image: $ANSIBLE_IMAGE
  before_script: *setup_ssh
  script:
    - echo "Run deploy ansible playbook"
    - >
      ansible-playbook -v .ansible/deploy-dev.yaml
      --private-key="~/.ssh/deploy"
      -i ".ansible/environments/dev/hosts"
      -e docker_registry_creds_username="\"$DOCKER_REGESTRY_USERNAME\""
      -e docker_registry_creds_password="\"$DOCKER_REGESTRY_PASSWORD\""
      -e docker_registry_creds_email="\"$DOCKER_REGESTRY_EMAIL\""
      -e docker_registry_url="\"$DOCKER_REGESTRY_URL\""
      -e docker_registry_project="\"$DOCKER_REGESTRY_PROJECT\""
      -e docker_repo_name="\"$DOCKER_REPO_NAME\""
      -e app_version="\"$CI_COMMIT_SHORT_SHA\""
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
