---
- name: Deploy project
  hosts: all

  tasks:
    - name: Login to the docker registry
      shell: docker login --username "{{ docker_registry_creds_username }}" --password "{{ docker_registry_creds_password }}" "{{ docker_registry_url }}"

    - name: Pull backend docker image
      shell: docker pull "{{ docker_registry_url }}/{{ docker_registry_project }}/{{ docker_repo_name }}:{{ app_version }}"

    - name: Check docker directory existence
      file:
        path: "/opt/dev-sapg"
        state: directory

    - name: Check config directories existence
      file:
        path: "/opt/dev-sapg/{{ item }}"
        state: directory
      with_items:
        - "nginx/conf"

    - name: Create templates
      template:
        src: templates/{{ item }}.j2
        dest: "/opt/dev-sapg/{{ item }}"
      with_items:
        - docker-compose-dev.yaml

    - name: Create nginx config file
      template:
        src: templates/{{ item }}.j2
        dest: "/opt/dev-sapg/nginx/conf/{{ item }}"
      with_items:
        - nginx.conf

    - name: Start docker compose
      shell: docker compose -f /opt/dev-sapg/docker-compose-dev.yaml up -d --build && docker compose -f /opt/dev-sapg/docker-compose-dev.yaml exec backend bash -c "php artisan optimize:clear && php artisan optimize && php artisan migrate --force && php artisan l5-swagger:generate"
